# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7722deee2f1a04ad065d7a13149ffe0341d41104f54cb75df4d662c7dd64011edd5db3d796ebf6cf6ae26bb3d392df3c8bddf09990896d43d1322920e164c924

test:
  secret_key_base: 8862ff6a931de59d9f35c001682e699e3a176908581f59724f727c86f2533bf29e961cdf956a5d40cc3241e935dc0478b9726cc3d93ef97030806709286d57eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
