# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398f7a2f3740d44abd8a8896fbfdfd96e0eef50fc0637082451e079411718208e313080da2fd0c48eeade69262df3787d769795c9a12ae9f4e69a0ad36cd9066

test:
  secret_key_base: 38f327b4422e8e7a9a40b958f9f7d4af0424c7875b535da5f429b75fb607d8a91fd0590d89602a780759067d45675b164068050bc310a69aa710b2c807f45afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
